#version 460 core

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in; // invocations

layout(binding = 0, r32ui) uniform uimage2D in_pixel_count;
layout(binding = 1, rgba16f) uniform image2D out_colour;

void main() {
    uint val = imageLoad(in_pixel_count, ivec2(gl_GlobalInvocationID.xy)).r;
    imageStore(out_colour, ivec2(gl_GlobalInvocationID.xy), vec4(0.0, abs(sin(val*0.01)), abs(cos(val*0.01))*val, 1.0));
}
